name: Sentry Release

on:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: npm install
    - name: Create environment.ts file
      run: |
        touch src/environments/environment.prod.ts && echo "${{ secrets.ENV_PROD }}" >> src/environments/environment.prod.ts
        touch src/environments/environment.ts && echo "${{ secrets.ENV_PROD }}" >> src/environments/environment.ts
    - name: Run Tests
      run: npm test -- --no-watch --browsers=ChromeHeadless --code-coverage      
    - run: npm run build
    - name: Create Sentry Release
      uses: getsentry/action-release@v1.3.1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      with:
        environment: production
        sourcemaps: './dist'
        set_commits: 'skip'      
